name: doctor_booking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.13
  go_router: ^13.2.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/Images/appointments.png
  - assets/Images/areuadoctor.png
  - assets/Images/consultations.png
  - assets/Images/consultations.png
  - assets/Images/doctors.png
  - assets/Images/healthArticles.png
  - assets/Images/Helpcentre.png
  - assets/Images/iso.png
  - assets/Images/medicalRecords.png
  - assets/Images/orders.png
  - assets/Images/payment.png
  - assets/Images/profileIcon.png
  - assets/Images/reminder.png
  - assets/Images/settings.png
  - assets/Images/testBooking.png
  - assets/Images/Calender.png
  - assets/Images/diabetes.png
  - assets/Images/consultdoc.jpeg
  - assets/Images/insurance.jpeg
  - assets/Images/image1.png
  - assets/Images/image2.png
  - assets/Images/image3.png
  - assets/Images/image4.png
  - assets/Images/ad1.jpeg
  - assets/Images/ad2.jpeg




