import 'package:equatable/equatable.dart';

class Doctor extends Equatable {
  final double latitude;
  final double longitude;
  final String clinicAddress;
  final String address;
  final String image;
  final String name;
  final String experience;
  final String phoneNo;
  final String id;
  final String degree;
  final String speciality;
  final double bookingFees;

  const Doctor(
      {required this.latitude,
      required this.longitude,
      required this.clinicAddress,
      required this.experience,
      required this.image,
      required this.address,
      required this.name,
      required this.phoneNo,
      required this.id,
      required this.degree,
      required this.speciality,
      required this.bookingFees});

  static List<Doctor> doctors = [
    const Doctor(
        latitude: 31.327266,
        longitude: 75.588791,
        clinicAddress: '123, Central Town, Jalandhar',
        address: 'Central Town',
        id: '1',
        image: 'https://shorturl.at/lLMQ8',
        name: "Dr. Veena Mattu",
        phoneNo: '+919464332899',
        degree: 'MBBS, F.E.M-RCGP(UK)',
        speciality: 'General Physician',
        bookingFees: 700,
        experience: '14 Years of Experience'),
    const Doctor(
        latitude: 31.19097,
        longitude: 75.34201,
        clinicAddress: '456, Nakodar Chownk, Jalandhar',
        address: 'Nakodar Chownk',
        image: "https://shorturl.at/nsOW0",
        experience: '8 Years of Experience',
        name: "Dr. Pawan Kumar Singh",
        phoneNo: "+919780110211",
        id: '2',
        degree: 'degree',
        speciality: 'MBBS',
        bookingFees: 300),
    const Doctor(
        latitude: 31.318134,
        longitude: 75.588173,
        clinicAddress: '789, BMC Chownk, Jalandhar',
        address: 'BMC Chownk',
        experience: '11 years of Experience',
        image: "https://shorturl.at/fhnpJ",
        name: "Dr Piyush Gulabrao Nikam",
        phoneNo: '+919780220321',
        id: '3',
        degree:
            "MBBS, MS - General Surgery, Fellowship in Minimal Access Surgery",
        speciality: "General Surgeon",
        bookingFees: 400),
    const Doctor(
        longitude: 31.317040,
        latitude: 75.577751,
        clinicAddress: '101, Guru Nanak Mission Chownk, Jalandhar',
        address: 'Guru Nanak Mission Chownk',
        experience: '13 years of Experience',
        image: 'https://shorturl.at/ilsw5',
        name: 'Dr Sunakshi Singh',
        phoneNo: '+917814473219',
        id: '4',
        degree: "MD - Dermatology, MBBS",
        speciality: 'Dermatologist',
        bookingFees: 1000),
    const Doctor(
        longitude: 31.333960,
        latitude: 75.562497,
        clinicAddress: '567,Kapurthala Chowk, Jalandhar',
        address: 'Kapurthala Chowk',
        experience: '8 years of Experience',
        image: 'https://shorturl.at/dhjGX',
        name: 'Dr Naveen Kumar',
        phoneNo: '+917814473219',
        id: '5',
        degree: 'MBBS, MS - General Surgery',
        speciality: 'General Surgeon',
        bookingFees: 500),
    const Doctor(
        longitude: 31.333960,
        latitude: 75.562497,
        clinicAddress: '890, Rama Mandi, Jalandhar',
        address: 'Rama Mandi',
        experience: '20 years of Experience',
        image: 'https://rb.gy/hbdgi4',
        name: "Dr. Ridhi Narang",
        phoneNo: '+919872183234',
        id: '6',
        degree: 'M.B.B.S, MS - Obstetrics and Gynaecology',
        speciality: 'Gynaecologist',
        bookingFees: 400),
    const Doctor(
        longitude: 31.317040,
        latitude: 75.577751,
        clinicAddress: '321, Jalandhar Cantt, Jalandhar',
        address: 'Jalandhar Cantt',
        experience: '5 years of Experience',
        image: "https://rb.gy/a0fpna",
        name: 'Dr Tushar Goel',
        phoneNo: '+919874320984',
        id: "7",
        degree: 'MBBS, MS - General Surgery',
        speciality: "General Surgeon",
        bookingFees: 500),
    const Doctor(
        latitude: 31.327266,
        longitude: 75.588791,
        clinicAddress: '654, Model Town, Jalandhar ',
        address: 'Model Town',
        experience: '9 years of Experience',
        image: 'https://rb.gy/6ipwm5',
        name: 'Dr Amit Kumar Kushwaha',
        phoneNo: '+919780113743',
        id: '8',
        degree: 'MBBS, MS - General Surgery',
        speciality: 'General Surgeon',
        bookingFees: 400),
    const Doctor(
        latitude: 31.318134,
        longitude: 75.588173,
        clinicAddress: '501, Urban Estate, Jalandhar',
        address: 'Urban State',
        experience: "12 years of Experience",
        image: 'https://rb.gy/3owop0',
        name: 'Dr Amit Kukreti',
        phoneNo: '+919780220432',
        id: '9',
        degree: 'MBBS, MS - General Surgery',
        speciality: 'General Surgeon',
        bookingFees: 500),
    const Doctor(
        longitude: 31.317040,
        latitude: 75.577751,
        clinicAddress: '543, Adarsh Nagar, Jalandhar',
        address: 'Adarsh Nagar',
        experience: '7 years of Experience',
        image: 'https://rb.gy/be6z27',
        name: 'Dr Sanjeev Gupta',
        phoneNo: '+919780220345',
        id: '10',
        degree: 'MBBS, MS - General Surgery',
        speciality: 'General Surgeon',
        bookingFees: 500),
    const Doctor(
        longitude: 31.333960,
        latitude: 75.562497,
        clinicAddress: '540, Green Model Town, Jalandhar',
        address: 'Green Model Town',
        experience: '6 years of Experience',
        image: "https://t.ly/JGJ7U",
        name: "Dr. N A Khan",
        phoneNo: '+919780220342',
        id: '11',
        degree: "Doctor In Unani Medicine(D.U.M.B.I.M)",
        speciality: "Sexologist",
        bookingFees: 500),
    const Doctor(
        longitude: 31.317040,
        latitude: 75.577751,
        clinicAddress: '5430, Kishanpura, Jalandhar',
        address: 'Kishanpura',
        experience: '10 years of Experience',
        image: 'https://t.ly/ykyuC',
        name: 'Dr. Yuvraj Arora Monga',
        phoneNo: "+919783298345",
        id: '12',
        degree: 'MBBS, MD - Pharmacology',
        speciality: "Sexologist",
        bookingFees: 800),
    const Doctor(
        latitude: 31.318134,
        longitude: 75.588173,
        clinicAddress: '23, Basti Sheikh, Jalandhar',
        address: 'Basti Sheikh',
        experience: '4 years of Experience',
        image: "https://t.ly/rC8BW",
        name: "Dr. Pooja Anand Sharma",
        phoneNo: "+917801104328",
        id: '13',
        degree: "Ph.D - Psychology, M.Sc. - Counselling and Psychotherapy,",
        speciality: "Psychologist",
        bookingFees: 2000),
    const Doctor(
        longitude: 31.333960,
        latitude: 75.562497,
        clinicAddress: '233, Shaheed Udham Singh Nagar, Jalandhar',
        address: 'Shaheed Udham Singh Nagar',
        experience: '8 years of Experience',
        image: "https://t.ly/EF9sj",
        name: "Dr. Vikas Khanna",
        phoneNo: "+919654398765",
        id: '14',
        degree: "BDS, Certification In Hypnotherapy",
        speciality: "Psychologist",
        bookingFees: 1800),
    const Doctor(
        latitude: 31.327266,
        longitude: 75.588791,
        clinicAddress: '203, Civil Lines, Jalandhar',
        address: 'Civil Lines',
        experience: '3 years of Experience',
        image: "https://t.ly/4Wuya",
        name: "Dr. Nisha Khanna",
        phoneNo: "+917089321754",
        id: "15",
        degree: "Ph. D - Psychology",
        speciality: "Psychologist",
        bookingFees: 6000),
    const Doctor(
        latitude: 31.19097,
        longitude: 75.34201,
        clinicAddress: '203, Maqsudan, Jalandhar',
        address: 'Maqsudan',
        experience: '3 years of Experience',
        image: "https://rb.gy/hy5ffg",
        name: "Dr. Swarnshikha Sharma",
        phoneNo: '+918790890987',
        id: '16',
        degree: "Doctrate In Dietetics, PhD - Psychology",
        speciality: "Dietitian/Nutritionist",
        bookingFees: 400),
    const Doctor(
        latitude: 31.318134,
        longitude: 75.588173,
        clinicAddress: '98, Avtar Nagar, Jalandhar',
        address: 'Avtar Nagar',
        experience: '12 years of Experience',
        image: "https://rb.gy/263ei0",
        name: 'Dt. Ritika Dua',
        phoneNo: '+919782134590',
        id: '17',
        degree: 'BSc-Diet & Nutrition, M.Sc-Diet & Nutrition',
        speciality: 'Dietitian/Nutritionist',
        bookingFees: 1000),
    const Doctor(
        longitude: 31.333960,
        latitude: 75.562497,
        clinicAddress: '928, Shaheed Bhagat Singh Nagar, Jalandhar',
        address: 'Shaheed Bhagat Singh Nagar',
        experience: '6 years of Experience',
        image: 'https://rb.gy/nv14j7',
        name: 'Dr. Vikas Yadav',
        phoneNo: "+917807432876",
        id: '18',
        degree: 'BDS',
        speciality: 'Dentist',
        bookingFees: 200),
    const Doctor(
        longitude: 31.333960,
        latitude: 75.562497,
        clinicAddress: '78, Guru Gobind Singh Nagar, Jalandhar',
        address: 'Guru Gobind Singh Nagar',
        experience: '9 years of Experience',
        image: 'https://rb.gy/r2pmnd',
        name: 'Dr. Sandeep Kumar Jangra',
        phoneNo: '+917865439876',
        id: '19',
        degree: 'MDS - Orthodontics, BDS, Certified Implantologist',
        speciality: 'Dentist',
        bookingFees: 500),
    const Doctor(
        longitude: 31.317040,
        latitude: 75.577751,
        clinicAddress: '378, Lajpat Nagar, Jalandhar',
        address: 'Lajpat Nagar',
        experience: '4 years of Experience',
        image: 'https://rb.gy/1nvd30',
        name: 'Dr. Ashok Yadav',
        phoneNo: '+919654588765',
        id: '20',
        degree: 'MDS - Orthodontics, BDS',
        speciality: 'Dentist',
        bookingFees: 300)
  ];
  @override
  List<Object?> get props => [
        image,
        name,
        phoneNo,
        id,
        degree,
        speciality,
        bookingFees,
      ];
}
