import 'package:equatable/equatable.dart';

class LabTest extends Equatable {
  final String name;
  final double price;
  final String id;
  final String time;

  const LabTest({
    required this.name,
    required this.price,
    required this.id,
    required this.time,
  });

  static List<LabTest> labtests = [
    const LabTest(
      name: 'CBC',
      price: 200,
      id: '1',
      time: '1 Day',
    ),
    const LabTest(
      name: 'BMP',
      price: 250,
      id: '2',
      time: '1 Day',
    ),
    const LabTest(
      name: 'CMP',
      price: 300,
      id: '3',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Lipid Panel',
      price: 180,
      id: '4',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Thyroid Stimulating Hormone (TSH)',
      price: 150,
      id: '5',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Urinalysis',
      price: 120,
      id: '6',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Electrocardiogram (ECG/EKG)',
      price: 350,
      id: '7',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Troponin Test',
      price: 280,
      id: '8',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Cardiac Enzyme Panel',
      price: 400,
      id: '9',
      time: '2 Days',
    ),
    const LabTest(
      name: 'Brain Natriuretic Peptide (BNP)',
      price: 320,
      id: '10',
      time: '1 Day',
    ),
    // Add more heart-related lab tests here...
    const LabTest(
      name: 'Cholesterol Panel',
      price: 280,
      id: '11',
      time: '1 Day',
    ),
    const LabTest(
      name: 'High-sensitivity C-reactive Protein',
      price: 150,
      id: '12',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Homocysteine Test',
      price: 200,
      id: '13',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Lipoprotein Test',
      price: 180,
      id: '14',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Stress Test',
      price: 450,
      id: '15',
      time: '2 Days',
    ),
    const LabTest(
      name: 'Echocardiogram',
      price: 500,
      id: '16',
      time: '2 Days',
    ),
    const LabTest(
      name: 'Coronary Calcium Scan',
      price: 350,
      id: '17',
      time: '2 Days',
    ),
    const LabTest(
      name: 'Holter Monitor',
      price: 300,
      id: '18',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Myocardial Perfusion Imaging',
      price: 600,
      id: '19',
      time: '2 Days',
    ),
    const LabTest(
      name: 'Cardiac Catheterization',
      price: 800,
      id: '20',
      time: '3 Days',
    ),
    const LabTest(
      name: 'Creatinine Test',
      price: 150,
      id: '21',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Blood Urea Nitrogen (BUN)',
      price: 130,
      id: '22',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Albumin Test',
      price: 120,
      id: '23',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Liver Function Panel',
      price: 280,
      id: '24',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Alanine Aminotransferase',
      price: 140,
      id: '25',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Aspartate Aminotransferase',
      price: 140,
      id: '26',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Gamma-Glutamyl Transferase ',
      price: 160,
      id: '27',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Alkaline Phosphatase (ALP)',
      price: 150,
      id: '28',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Total Bilirubin Test',
      price: 160,
      id: '29',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Prothrombin Time (PT)',
      price: 170,
      id: '30',
      time: '1 Day',
    ),
    const LabTest(
      name: 'STD Panel',
      price: 300,
      id: '31',
      time: '2 Days',
    ),
    const LabTest(
      name: 'HIV Test',
      price: 150,
      id: '32',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Chlamydia Test',
      price: 100,
      id: '33',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Gonorrhea Test',
      price: 100,
      id: '34',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Syphilis Test',
      price: 120,
      id: '35',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Herpes Simplex Virus (HSV) Test',
      price: 130,
      id: '36',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Human Papillomavirus (HPV) Test',
      price: 150,
      id: '37',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Testosterone Test',
      price: 200,
      id: '38',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Estrogen Test',
      price: 180,
      id: '39',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Progesterone Test',
      price: 180,
      id: '40',
      time: '1 Day',
    ),
    const LabTest(
      name: 'MRI Scan',
      price: 600,
      id: '41',
      time: '2 Days',
    ),
    const LabTest(
      name: 'CT Scan',
      price: 500,
      id: '42',
      time: '1 Day',
    ),
    const LabTest(
      name: 'X-ray',
      price: 150,
      id: '43',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Electroencephalogram (EEG)',
      price: 350,
      id: '44',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Cerebrospinal Fluid (CSF) Analysis',
      price: 400,
      id: '45',
      time: '2 Days',
    ),
    const LabTest(
      name: 'Brain MRI with Contrast',
      price: 800,
      id: '46',
      time: '2 Days',
    ),
    const LabTest(
      name: 'Carotid Ultrasound',
      price: 300,
      id: '47',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Transcranial Doppler (TCD)',
      price: 400,
      id: '48',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Brain Angiography',
      price: 900,
      id: '49',
      time: '3 Days',
    ),
    const LabTest(
      name: 'Brain PET Scan',
      price: 1000,
      id: '50',
      time: '3 Days',
    ),
    const LabTest(
      name: 'Carotid Angiography',
      price: 850,
      id: '51',
      time: '3 Days',
    ),
    const LabTest(
      name: 'Coronary Angiography',
      price: 1200,
      id: '52',
      time: '3 Days',
    ),
    const LabTest(
      name: 'Peripheral Angiography',
      price: 1100,
      id: '53',
      time: '3 Days',
    ),
    const LabTest(
      name: 'Nuclear Stress Test',
      price: 700,
      id: '54',
      time: '2 Days',
    ),
    const LabTest(
      name: 'Cardiac CT Angiography',
      price: 900,
      id: '55',
      time: '2 Days',
    ),
    const LabTest(
      name: 'Echocardiogram with Doppler',
      price: 550,
      id: '56',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Holter Monitor',
      price: 300,
      id: '57',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Cardiac MRI',
      price: 750,
      id: '58',
      time: '2 Days',
    ),
    const LabTest(
      name: 'Cardiac PET Scan',
      price: 900,
      id: '59',
      time: '3 Days',
    ),
    const LabTest(
      name: 'Coronary Calcium Scan',
      price: 500,
      id: '60',
      time: '2 Days',
    ),
    const LabTest(
      name: 'Body Mass Index (BMI) Calculation',
      price: 50,
      id: '61',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Body Fat Percentage Measurement',
      price: 60,
      id: '62',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Waist-to-Hip Ratio Measurement',
      price: 40,
      id: '63',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Resting Metabolic Rate (RMR) Measurement',
      price: 70,
      id: '64',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Basal Metabolic Rate (BMR) Measurement',
      price: 65,
      id: '65',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Lean Body Mass Measurement',
      price: 55,
      id: '66',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Body Composition Analysis',
      price: 80,
      id: '67',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Vital Signs Measurement',
      price: 30,
      id: '68',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Electrocardiogram (ECG/EKG)',
      price: 70,
      id: '69',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Pulse Oximetry Test',
      price: 40,
      id: '70',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Physical Fitness Assessment',
      price: 90,
      id: '71',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Flexibility Test',
      price: 50,
      id: '72',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Muscle Strength Test',
      price: 60,
      id: '73',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Cardiorespiratory Endurance Test',
      price: 80,
      id: '74',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Balance and Stability Test',
      price: 55,
      id: '75',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Gait Analysis',
      price: 70,
      id: '76',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Posture Analysis',
      price: 50,
      id: '77',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Bone Density Test',
      price: 85,
      id: '78',
      time: '2 Days',
    ),
    const LabTest(
      name: 'Joint Range of Motion Test',
      price: 60,
      id: '79',
      time: '1 Day',
    ),
    const LabTest(
      name: 'Body Temperature Measurement',
      price: 25,
      id: '80',
      time: '1 Day',
    ),
  ];

  @override
  List<Object?> get props => [
        name,
        id,
        price,
        time,
      ];
}
