// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWikPgfCW1qF8mXJpirQmGS_9HrLe061o',
    appId: '1:398422602218:web:5593df824cb7f049290293',
    messagingSenderId: '398422602218',
    projectId: 'doctor-booking-app-70f09',
    authDomain: 'doctor-booking-app-70f09.firebaseapp.com',
    storageBucket: 'doctor-booking-app-70f09.appspot.com',
    measurementId: 'G-9DLGMTHLYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9agXJTkNDQaQWn7sSgCFFVSuXXPfOuis',
    appId: '1:398422602218:android:bdcea3353c420286290293',
    messagingSenderId: '398422602218',
    projectId: 'doctor-booking-app-70f09',
    storageBucket: 'doctor-booking-app-70f09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvYr_V52lbpaUgl5Wb2a8y2ntdxzFEsME',
    appId: '1:398422602218:ios:83d9715568fce7a4290293',
    messagingSenderId: '398422602218',
    projectId: 'doctor-booking-app-70f09',
    storageBucket: 'doctor-booking-app-70f09.appspot.com',
    iosBundleId: 'com.example.doctorBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvYr_V52lbpaUgl5Wb2a8y2ntdxzFEsME',
    appId: '1:398422602218:ios:a782cfd9f89f0e4d290293',
    messagingSenderId: '398422602218',
    projectId: 'doctor-booking-app-70f09',
    storageBucket: 'doctor-booking-app-70f09.appspot.com',
    iosBundleId: 'com.example.doctorBookingApp.RunnerTests',
  );
}
